[package]
name = "forwarder_guest"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
env_logger = "0.11.5"
forwarder = { path = "../../libs/libforwarder" }
log = "0.4.22"
poll_token_derive = "0.1.0"
remain = "0.2.14"
vmm-sys-util = "0.12.1"

[package.metadata.deb]
maintainer = "ferrochrome-dev@google.com"
copyright = "2024, The Android Open Source Project"
depends = "$auto"
